services:
  webapp:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: tvnews