services:
  webapp:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ['pytest']

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - ./database:/var/lib/postgresql/data
    
    environment:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: tvnews

    healthcheck:
      test: ["CMD-SHELL", "sh", "-c", "pg_isready", "-i", "-U", "fastapi", "-d", "tvnews"]
      interval: 5s
      timeout: 5s
      retries: 5