services:
  webapp:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - ./database:/var/lib/postgresql/data
    
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: tvnews

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi tvnews"]
      interval: 5s
      timeout: 5s
      retries: 5