name: Python application TvNews

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start containers
      run: docker compose -f "compose.yaml" up -d --build

    - name: List containers running
      run: docker ps

    - name: Run tests pytest
      run: docker exec -t tvnews-webapp-1 pytest

    - name: Install Chrome driver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '88.0.4324.96'

    - name: Run selenium tests
      run: python ./tests_app_shell/test_selenium.py

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Ftp sending
      run: echo '???'