name: Python application TvNews

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-my-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start containers
      run: docker compose -f "compose.yaml" up -d --build

    - name: List containers running
      run: docker ps

    - name: Run tests
      run: docker exec -it tvnews-postgres-1 pytest

    # - name: Stop containers
    #   if: always()
    #   run: docker compose -f "compose.yaml" down
